# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspectos', '0002_auto_20170327_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion_mandibular',
            name='apertura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcion_mandibular',
            name='desv_afmp_derecho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcion_mandibular',
            name='desv_afmp_izquierdo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcion_mandibular',
            name='signos_sintomas_atm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes_afmp',
            name='nombreimagen',
            field=models.CharField(blank=True, default='Sin nombre', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='canina_derecha',
            field=models.IntegerField(blank=True, choices=[(1, b'Clase 1'), (2, b'Clase 2'), (3, b'Clase 3'), (4, b'CC'), (5, b'N.E.')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='canina_izquierda',
            field=models.IntegerField(blank=True, choices=[(1, b'Clase 1'), (2, b'Clase 2'), (3, b'Clase 3'), (4, b'CC'), (5, b'N.E.')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='escalon_distal',
            field=models.IntegerField(blank=True, choices=[(1, b'Derecho'), (2, b'Izquierdo')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='escalon_mesial',
            field=models.IntegerField(blank=True, choices=[(1, b'Derecho'), (2, b'Izquierdo')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='molar_derecha',
            field=models.IntegerField(blank=True, choices=[(1, b'Clase 1'), (2, b'Clase 2'), (3, b'Clase 3'), (4, b'CC'), (5, b'N.E.')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='molar_izquierda',
            field=models.IntegerField(blank=True, choices=[(1, b'Clase 1'), (2, b'Clase 2'), (3, b'Clase 3'), (4, b'CC'), (5, b'N.E.')], null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relaciones_sagitales',
            name='plano_termina_recto',
            field=models.IntegerField(blank=True, choices=[(1, b'Derecho'), (2, b'Izquierdo')], null=True),
        ),
    ]
