# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivo_consulta',
            name='fechaRegistro',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 11, 34, 8, 139000, tzinfo=utc)),
        ),
    ]
