# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico_cefalometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_esqueletal', models.IntegerField(choices=[(1, b'Clase 1'), (2, b'Clase 2'), (3, b'Clase 3')])),
                ('tipo_de_crecimiento', models.IntegerField(choices=[(1, b'Neutro'), (2, b'Vertical'), (3, b'Horizontal')])),
                ('medidas_dentales', models.IntegerField(choices=[(1, b'Retro inclinado'), (2, b'Pro inclinaci\xc3\xb3n'), (3, b'Normo inclinaci\xc3\xb3n')])),
                ('otro_patron', models.CharField(blank=True, max_length=100, null=True)),
                ('medidas_esteticas', models.TextField(max_length=500)),
            ],
        ),
    ]
