# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crecimiento',
            fields=[
                ('id_Crecimiento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_de_crecimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='diagnostico_cefalometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro_patron', models.TextField()),
                ('medidas_esteticas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MDentales',
            fields=[
                ('id_MDentales', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medidas_dentales', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id_Patron', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patron_esqueletal', models.CharField(max_length=50)),
            ],
        ),
    ]
