# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico_cefalometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_esqueletal', models.TextField()),
                ('tipo_de_crecimiento', models.TextField()),
                ('medidas_dentales', models.TextField()),
                ('medidas_esteticas', models.TextField()),
            ],
        ),
    ]
