# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacion', '0002_auto_20170708_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfacial', models.ImageField(blank=True, null=True, upload_to='paciente/pfacial/')),
                ('pfrontal', models.ImageField(blank=True, null=True, upload_to='paciente/pfrontal/')),
                ('psonrisa', models.ImageField(blank=True, null=True, upload_to='paciente/psonrisa/')),
                ('osuperior', models.ImageField(blank=True, null=True, upload_to='paciente/osuperior/')),
                ('oinferior', models.ImageField(blank=True, null=True, upload_to='paciente/oinferior/')),
                ('lizquierdo', models.ImageField(blank=True, null=True, upload_to='paciente/lizquierdo/')),
                ('lderecho', models.ImageField(blank=True, null=True, upload_to='paciente/lderecho/')),
                ('frontal', models.ImageField(blank=True, null=True, upload_to='paciente/frontal/')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
    ]
