# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='img_paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfacial', models.ImageField(blank=True, null=True, upload_to='paciente/pfacial/')),
                ('pfrontal', models.ImageField(blank=True, null=True, upload_to='paciente/pfrontal/')),
                ('psonrisa', models.ImageField(blank=True, null=True, upload_to='paciente/psonrisa/')),
                ('osuperior', models.ImageField(blank=True, null=True, upload_to='paciente/osuperior/')),
                ('oinferior', models.ImageField(blank=True, null=True, upload_to='paciente/oinferior/')),
                ('lizquierdo', models.ImageField(blank=True, null=True, upload_to='paciente/lizquierdo/')),
                ('lderecho', models.ImageField(blank=True, null=True, upload_to='paciente/lderecho/')),
                ('frontal', models.ImageField(blank=True, null=True, upload_to='paciente/frontal/')),
            ],
        ),
        migrations.CreateModel(
            name='img_paciente2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfacial2', models.ImageField(blank=True, null=True, upload_to='paciente/pfacial/')),
                ('pfrontal2', models.ImageField(blank=True, null=True, upload_to='paciente/pfrontal/')),
                ('psonrisa2', models.ImageField(blank=True, null=True, upload_to='paciente/psonrisa/')),
                ('osuperior2', models.ImageField(blank=True, null=True, upload_to='paciente/osuperior/')),
                ('oinferior2', models.ImageField(blank=True, null=True, upload_to='paciente/oinferior/')),
                ('lizquierdo2', models.ImageField(blank=True, null=True, upload_to='paciente/lizquierdo/')),
                ('lderecho2', models.ImageField(blank=True, null=True, upload_to='paciente/lderecho/')),
                ('frontal2', models.ImageField(blank=True, null=True, upload_to='paciente/frontal/')),
            ],
        ),
    ]
