# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_auto_20170717_1444'),
        ('gestorImg', '0002_auto_20170717_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osupm', models.ImageField(blank=True, null=True, upload_to='modelo/osuperior/')),
                ('oinfm', models.ImageField(blank=True, null=True, upload_to='modelo/oinferior/')),
                ('lizqm', models.ImageField(blank=True, null=True, upload_to='modelo/lizquierdo/')),
                ('frontm', models.ImageField(blank=True, null=True, upload_to='modelo/frontal/')),
                ('lderm', models.ImageField(blank=True, null=True, upload_to='modelo/lderecho/')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
    ]
