# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorImg', '0002_img_paciente2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='frontal',
            new_name='frontal2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='lderecho',
            new_name='lderecho2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='lizquierdo',
            new_name='lizquierdo2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='oinferior',
            new_name='oinferior2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='osuperior',
            new_name='osuperior2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='pfacial',
            new_name='pfacial2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='pfrontal',
            new_name='pfrontal2',
        ),
        migrations.RenameField(
            model_name='img_paciente2',
            old_name='psonrisa',
            new_name='psonrisa2',
        ),
    ]
