# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0004_auto_20170720_1158'),
        ('gestorImg', '0003_img_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_aparato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparatof', models.ImageField(blank=True, null=True, upload_to='aparato/frontal/')),
                ('aparatol', models.ImageField(blank=True, null=True, upload_to='aparato/lateral/')),
                ('aparato', models.ImageField(blank=True, null=True, upload_to='aparato/arriba/')),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
    ]
