# -*- coding: utf-8 -*-
aparato_choices = (
    (1, ("Ortodoncia Fija")),
    (2, ("Botón de Nance")),
    (3, ("Botón de Nance")),
    (4, ("Arco Lingua")),
    (5, ("Tornillo Hirax")),
    (6, ("Barra Transpalatina")),
    (7, ("Botones")),
    (8, ("SN1")),
    (9, ("SN2")),
    (10, ("SN3")),
    (11, ("SN4")),
    (12, ("SN5")),
    (13, ("SN6")),
    (14, ("SN7")),
    (15, ("SN8")),
    (16, ("SN9")),
    (17, ("SN10")),
    (18, ("Pistas Planas Directas")),
    (19, ("Pistas Planas Indirectas")),
    (20, ("Aparato Bimler")),
    (21, ("Bionator")),
    (22, ("Otros")),
)