# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7)),
                ('numero', models.IntegerField()),
                ('fichas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas')),
            ],
        ),
    ]
