# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aspectos_mandibulares1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rama_mand_anch_izq_altura', models.IntegerField()),
                ('rama_mand_anch_der_altura', models.IntegerField()),
                ('rama_mand_anch_simetrico', models.IntegerField(choices=[(1, b'Simetrica'), (0, b'Asimetrica')])),
                ('rama_mand_anch_izq_aspect_observ', models.TextField()),
                ('rama_mand_anch_der_aspect_observ', models.TextField()),
                ('rama_mand_altur_izq_altura', models.IntegerField()),
                ('rama_mand_altur_der_altura', models.IntegerField()),
                ('rama_mand_altur_simetrico', models.IntegerField(choices=[(1, b'Simetrica'), (0, b'Asimetrica')])),
                ('rama_mand_altur_izq_aspect_observ', models.TextField()),
                ('rama_mand_altur_der_aspect_observ', models.TextField()),
                ('cuerpo_mand_altur_izq_altura', models.IntegerField()),
                ('cuerpo_mand_altur_der_altura', models.IntegerField()),
                ('cuerpo_mand_altur_simetrico', models.IntegerField(choices=[(1, b'Simetrica'), (0, b'Asimetrica')])),
                ('cuerpo_mand_altur_izq_aspect_observ', models.TextField()),
                ('cuerpo_mand_altur_der_aspect_observ', models.TextField()),
                ('cuerpo_mand_long_izq_altura', models.IntegerField()),
                ('cuerpo_mand_long_der_altura', models.IntegerField()),
                ('cuerpo_mand_long_simetrico', models.IntegerField(choices=[(1, b'Simetrica'), (0, b'Asimetrica')])),
                ('cuerpo_mand_long_izq_aspect_observ', models.TextField()),
                ('cuerpo_mand_long_der_aspect_observ', models.TextField()),
            ],
        ),
    ]
