# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspMandibular', '0002_auto_20170124_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspectos_mandibulares1',
            name='cod_expediente',
        ),
    ]
