# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas_general',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citas_general',
            name='fichas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas'),
        ),
        migrations.AddField(
            model_name='citas',
            name='fichas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas'),
        ),
    ]
