# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_cefalometrico', '0001_initial'),
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis_cefalometrico',
            name='fichas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informacion.fichas'),
        ),
        migrations.AddField(
            model_name='analisis_cefalometrico',
            name='numero_de_examen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analisis_cefalometrico.examen'),
        ),
    ]
