# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico_general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico_ortodontico_general', models.TextField()),
                ('problemas', models.TextField()),
                ('objetivos', models.TextField()),
                ('tratamiento', models.IntegerField(choices=[(1, b'Ortodoncia Preventiva'), (2, b'Ortodoncia Interceptiva'), (3, b'Ortopedia'), (4, b'Ortodoncia Fija')])),
                ('descripcion_tratamiento', models.TextField()),
            ],
        ),
    ]
